################
### MONITORS ###
################

# Laptop Monitors
monitor = eDP-1, preferred, 0x0, 1

# Disable laptop screen if lid is closed
bindl = , switch:on:Lid Switch, exec, ~/.local/bin/handle-lid close
bindl = , switch:off:Lid Switch, exec, ~/.local/bin/handle-lid open
